#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

# takes suggestions for possible socket locations as arguments, and prints the first one that is a socket
print_first_socket() {
  while [[ $# -gt 0 ]]; do
    if [ -S "$1" ]; then
      echo "$1"
      return 0
    fi
    shift
  done
  return 1
}

print_first_socket \
  "${XDG_RUNTIME_DIR:-""}/docker.sock" \
  /var/run/docker.sock \
  /run/docker.sock
